### ISSUE TITLE
[TRANSLATION] Text and no link to library in case library is empty

### ISSUE THREAD

**Issue by techpool** [Pratilipi-Growth/ecs-web#2]
![image](https://user-images.githubusercontent.com/13390045/37956322-9e25cdc6-31c8-11e8-9a5b-7c61325db3d4.png)
Need design for no contents in library

**Comment by libinvbabu** [comment]
Fixed it here: https://github.com/Pratilipi-Growth/ecs-web/commit/ed129122b6d1f78b0632a83e6730fb31e2c7da96
